version: "3"
services: 
  display:
    container_name: php-display
    volumes:
      - ./mometrix-display/src:/var/www/html/
    build: 
      context: php
      dockerfile: Dockerfile
    ports: 
      - 8000:5000
  #   links: 
  #     - database
  # database:
  #   image: "mometrix-mysql"